### ISSUE TITLE
IPID选项卡显示不全

### ISSUE THREAD

**Issue by CCCougar** [0xlane/com-process-inject#1]
不知道你有没有遇到过这种情况，符号表是通过IDA下载的，但打开IPID选项卡只显示了3个方法，其他方法没有显示出来：

![image](https://github.com/0xlane/com-process-inject/assets/44094753/659730ac-73d6-44dc-84f8-3ceed1749d16)

**Comment by 0xlane** [comment]
确保在 IDA 里能看到这个虚表对应的符号信息，看不到的话可能是win11没有这些符号了，看得到在ole里看不到的话可能就是oleviewdotnet 兼容性问题了吧毕竟不更新了，建议用 win10 试一下

**Comment by 0xlane** [comment]
你这个，combase.pdb是自己放到这个目录的吧，目录格式不对。得配置 `_NT_SYMBOL_PATH` 环境变量让调试器自动下载符号到这个目录里

**Comment by 0xlane** [comment]
oleview毕竟不更新了，有问题也很正常，也不必执着非用它不可，实际可能意义不大

**Comment by CCCougar** [comment]
换了一个Windows版本果然好了！多谢指点！主要是想通过具体函数名称看看能不能找到其他有趣的接口或方法：
![image](https://github.com/0xlane/com-process-inject/assets/44094753/05dca4b7-6d55-49a4-9976-4d0ef3172297)
比如这个Index为10的方法`DoNonreentrantCallback`我觉得可能也是有一个有趣的目标，结果IDA打开发现还是实际调用了`DoCallback`：
![image](https://github.com/0xlane/com-process-inject/assets/44094753/83b9a4db-65f4-4a64-a3a3-3f23138911ac)
只有`IID`的区别，也没什么意义
